### ISSUE TITLE
五星武器猎人之径被动效果无效

### ISSUE THREAD

**Issue by ighlES** [Frontrooms/3.0-Resources#4]
![7KZYAL )3(PN`)YROM(HNCL](https://user-images.githubusercontent.com/61189870/181826967-13a36b18-32b6-4d5e-8345-c73e56383240.png)

**Comment by millet6** [comment]
Please write more descriptive questions in English  请使用英文描述问题

**Comment by AceVenturaz** [comment]
Excel issue and known
